- name: Love actions for Windows
  id: build-packages
  uses: love-actions/love-actions-windows@v1.1.3
  with:
    love-package: ./snek.love
    # icon-path: ./assets/windows/icon.ico
    rc-path: ../.luarc.json
    product-name: snek
    app-id: snek
    output-folder: "./dist"